### ISSUE TITLE
Minimap not moved

### ISSUE THREAD

**Issue by Xioshock** [Rerago/LoLWideScreenFix#1]
Hello, thank you for the mod. I justtried it and the UI moves to the center, but the minimap is still in the corner, do you know if it's because of some UI settings, or if it stopped working altogether?

**Comment by Rerago** [comment]
Yes, unfortunately, an update seems to have put stones in our way. I will look at the problem in the next few days and try to fix it, if possible.

**Comment by Xioshock** [comment]
Hi, I just tried v0.3 and so far it looks almost perfect. I tried it on 1460p, and everything exept the minimap is centered, when I scale the minimap, it moves slightly towards the edge: https://ibb.co/hBTfxnN

Thank you for the mod :)

**Comment by Rerago** [comment]
Great :). Yes, I also have the minimap problem. But unfortunately can not be fixed properly due to the changed fixation. I have set the scaling to 34 or 35%, so it is just right at 1920p.
