### ISSUE TITLE
Nothing is Working

### ISSUE THREAD

**Issue by Zhanyee** [Rerago/LoLWideScreenFix#11]
I'm sorry if I'm dumb, but I have no idea how this works

I installed .net 6.0

I downloaded the executable file, put it in a separate folder and ran it, nothing happened

I moved the .exe file to the league of legends folder, nothing happened

I tried using the line of code provided directly in cmd and nothing happened

Is there any step by step tutorial on how to install the program and get this working?

**Comment by thoikochoidau** [comment]
same issue...

**Comment by Rerago** [comment]
Since you both have the same problem I would say we discuss this further in #12 and I close this issue here.
