### ISSUE TITLE
How can i use it !solved

### ISSUE THREAD

**Issue by thoikochoidau** [Rerago/LoLWideScreenFix#12]
Your .exe file doesn't work, how can i contact you ? 
I need some help :((

**Comment by thoikochoidau** [comment]
!solve
thanks to chatgpt
So i have to disable windows defender first, then put LoLWideScreenFix.exe into game folder

then run cmd at administrator, 
cd C:\Riot Games\League of Legends\

LoLWideScreenFix.exe -l "C:\Riot Games\League of Legends" -o "C:\Users\YOURUSERNAME\Desktop\output" -t 1920 -m LOLCUSTOMSKIN_MOD

Remember to create "output" folder first

**Comment by Rerago** [comment]
Where the `LoLWideScreenFix.exe` is located does not really matter, it does not have to be in the LoL folder. Let's assume that it is located on the desktop. Then the call would be as follows:

- open cmd (admin should not be necessary)
- change to the folder where the `LoLWideScreenFix.exe` is located
```cmd
cd %USERPROFILE%\Desktop\
```
- make sure that the output folder exists
```cmd
mkdir "%USERPROFILE%\Desktop\output"
```
- run LoLWideScreenFix
```cmd
LoLWideScreenFix.exe -l "C:\Riot Games\League of Legends" -o "%USERPROFILE%\Desktop\output" -t 1920 -m 2
```

By the way, Riot seems to have changed the structure again in the current patch. Therefore `LoLWideScreenFix` will probably not output anything currently.

**Comment by Rerago** [comment]
I have released a new version. Please check if v0.6 works.

**Comment by thoikochoidau** [comment]
> I have released a new version. Please check if v0.6 works.

let me <3

**Comment by thoikochoidau** [comment]
yup, this works.
But when i change minimap size, the minimap hud moving too...
does it normal ?

**Comment by Rerago** [comment]
Do you mean this one? #3

**Comment by thoikochoidau** [comment]
![image](https://user-images.githubusercontent.com/68668401/224507530-4aeb9501-417f-4684-a432-909921d171bd.png)
i've found a way to (kinda) solved this problem.....

**Comment by robertstratton630** [comment]
hey buddy, where abouts do i put the META / WAD folder after running the .exe?
