### ISSUE TITLE
!solved | can you close this issue xD sorry for bothering u| League updated to 64bit, so the scrpit broken again...

### ISSUE THREAD

**Issue by thoikochoidau** [Rerago/LoLWideScreenFix#14]
Help us, Rerago
We need you 🥲

**Comment by Rerago** [comment]
Mh so I have just tested it. Everything works for me. Did you recreate it after the patch? And if so, did you have used the latest versions?

https://github.com/Rerago/LoLWideScreenFix/releases
https://github.com/LeagueToolkit/cslol-manager/releases

**Comment by thoikochoidau** [comment]
![image](https://user-images.githubusercontent.com/68668401/230629464-246dae3f-8bc3-4f2b-b0b0-4e2da7b3eb7c.png)
![image](https://user-images.githubusercontent.com/68668401/230629702-5e93b47c-5642-475b-81dd-e86f13ec6465.png)
![image](https://user-images.githubusercontent.com/68668401/230629764-39f708db-fca0-4b3f-bec7-e0be9c453bcb.png)
I'm pretty sure I updated everything into lasted version...

**Comment by lilosenpai** [comment]
> Mh so I have just tested it. Everything works for me. Did you recreate it after the patch? And if so, did you have used the latest versions?
> 
> https://github.com/Rerago/LoLWideScreenFix/releases https://github.com/LeagueToolkit/cslol-manager/releases

Its also not working here for me, all updated, but something that op did not say is, the wad file is being created ok, the issue at least for me is that even with the mod on cslol manager, its not working in game, prevously we couldnt create the wad file, now the file is being created normally, but in game is not doing anything

**Comment by lilosenpai** [comment]
I did a new test and have news, i tried to make a wad for the 1920 resolution and its working, but what i used to use was 1600 and now its not working anymore and op uses 1500, maybe only 1920 is working, could you test @thoikochoidau ?

**Comment by lilosenpai** [comment]
> ![image](https://user-images.githubusercontent.com/68668401/230629464-246dae3f-8bc3-4f2b-b0b0-4e2da7b3eb7c.png) ![image](https://user-images.githubusercontent.com/68668401/230629702-5e93b47c-5642-475b-81dd-e86f13ec6465.png) ![image](https://user-images.githubusercontent.com/68668401/230629764-39f708db-fca0-4b3f-bec7-e0be9c453bcb.png) I'm pretty sure I updated everything into lastest version...

I was having problem to make it work and now its working, what i did was select the league of legend exe again in cslol manager, maybe try that because i also was having the following problem, the wad creation is okay, but in game was not working, then i went into the cslol manager setting the manually selected the lol exe again
