### ISSUE TITLE
Error on call

### ISSUE THREAD

**Issue by stubenhocker1337** [Rerago/LoLWideScreenFix#16]
input:

.\LoLWideScreenFix -l "D:\Riot Games\League of Legends" -o "C:\Users\User\portableApps\LoLWideScreenFix\output" -t 2560 -m 1

output:

 FAILED (Decompressed content size cannot be determined (e.g. invalid magic number, srcSize too small))

**Comment by stubenhocker1337** [comment]
> input:
> 
> .\LoLWideScreenFix -l "D:\Riot Games\League of Legends" -o "C:\Users\User\portableApps\LoLWideScreenFix\output" -t 2560 -m 1
> 
> output:
> 
> FAILED (Decompressed content size cannot be determined (e.g. invalid magic number, srcSize too small))

managed to get it working by outputting not raw but a lolcustomskin file

**Comment by Rerago** [comment]
Mh so with [v0.7.1](https://github.com/Rerago/LoLWideScreenFix/releases/tag/v0.7.1) this error should not occur anymore. Therefore I close the issue for now. If the error still occurs on v0.7.1 please just reopen this issue.
