### ISSUE TITLE
New patch 13.9 is having issues

### ISSUE THREAD

**Issue by javigoncompte** [Rerago/LoLWideScreenFix#17]
New patch 13.9 is having issues it crashes game when it tries to start

**Comment by Rerago** [comment]
So with the latest version of [cslol-manager](https://github.com/LeagueToolkit/cslol-manager) and with [v0.7.1](https://github.com/Rerago/LoLWideScreenFix/releases/tag/v0.7.1) it works for me without crash (but as we all know, that doesn't necessarily mean anything).

If the error still occurs with you, you have to look in the LoL logs. There you might find a hint what causes your crash. If you find something you can post it and I will check if I can do something.

However, if it is currently running again for you, you can also close the issue.

**Comment by javigoncompte** [comment]
ok got it just had to update cslol manager
