### ISSUE TITLE
Required option 'o, outputpath' is missing.

### ISSUE THREAD

**Issue by jaredweinfurtner** [Rerago/LoLWideScreenFix#2]
Version: `LoLWideScreenFix 0.3`

When executing the program:

`.\LoLWideScreenFix.exe -l "C:\Riot Games\League of Legends\" -o "C:\Riot Games\ultrawide-fix\" -t 2560`

I receive the following error:

```
ERROR(S):
  Required option 'o, outputpath' is missing.
```

I have tried both `-o` and `--outputpath` without luck.  I even tried re-ordering the arguments.

**Comment by Rerago** [comment]
This seems like an error in `CommandLineParser` (But I'm already thinking about switching to "System.CommandLine"). If you write this way it works for me:

`.\LoLWideScreenFix.exe -l "C:\Riot Games\League of Legends" -o "C:\Riot Games\ultrawide-fix" -t 2560`

If it works, please let me know.

**Comment by Rerago** [comment]
closed since no feedback was received
