### ISSUE TITLE
Can't run command line

### ISSUE THREAD

**Issue by GrosseQueueNoire** [Rerago/LoLWideScreenFix#4]
Hello,

So I created a shortcut of LoLWideScreenFix.exe and I cannot get any folder to be created. Here is my command line:

C:\LoLUW\LoLWideScreenFix.exe -l "C:\Riot Games\League of Legends" -o "C:\LoL Manager\cslol-manager\installed" -t 1920 -m 2

I don't get it. Could anybody tell me what's wrong with that line?

**Comment by Rerago** [comment]
Hello, have you run the whole thing from a console/cmd? And if yes, do you get an error message/output?

I have run this exact line and it runs through without error. Do you perhaps not have [.NET 5.0 Runtime (x64)](https://dotnet.microsoft.com/download/dotnet/5.0/runtime) installed?

**Comment by GrosseQueueNoire** [comment]
Wow, thank you, that was the problem. I didn't have .NET 5.0 Runtime (x64) installed.
