### ISSUE TITLE
Is it work for JP client?

### ISSUE THREAD

**Issue by tlserver** [Rerago/LoLWideScreenFix#5]
I run `.\LoLWideScreenFix.exe -l . -o .. -t 1920 -m 1` and I am getting this error:
```
PS C:\Riot Games\League of Legends>  .\LoLWideScreenFix.exe -l . -o .. -t 1920 -m 1
LoLWideScreenFix v0.3
=====================

[23:51:44] LoL directory:       .
[23:51:44] Output directory:    ..
[23:51:44] target resolution :  1920p


[23:51:44] Create RAW-ModFolder:        FAILED (Global.wad.client not found)
```
I have installed the JP client. Is it do not work for that? I found that in C:\Riot Games\League of Legends\\** there is no *.wad.client files.

**Comment by Rerago** [comment]
The problem seems to be the `.` at the path. Unfortunately, the application did not translate them correctly.

The problem should be fixed with v0.4 (which I just uploaded).

**Comment by tlserver** [comment]
But I also tried with absolute path before but I get the same error.

**Comment by Rerago** [comment]
Have you tried [v0.4](https://github.com/Rerago/LoLWideScreenFix/releases/tag/v0.4)?

If it doesn't work with that version either, I'll have to download the Japanese client (takes me a while, as my internet is very slow) and try it myself. But we get that already solved.

**Comment by tlserver** [comment]
I have tried version 0.4, but I still need to put LoLWideScreenFix.exe in another path, otherwise the following message appears and the whole game is deleted.

```
PS C:\Riot Games\League of Legends> .\LoLWideScreenFix.exe -l . -o .. -t 1920 -m 1
LoLWideScreenFix v0.4
=====================

[19:18:57] LoL directory:       C:\Riot Games\League of Legends
[19:18:57] Output directory:    C:\Riot Games
[19:18:57] target resolution :  1920p


[19:18:59] Create RAW-ModFolder:        FAILED (Access to the path 'LoLWideScreenFix.exe' is denied.)
```

**Comment by Rerago** [comment]
Super that it works now. I have now added a [change](https://github.com/Rerago/LoLWideScreenFix/commit/cb2c655b4e54854bc0f2cd419957c880ad076a31) so that uninvolved files (like the LoL folder) are not deleted.

The changes come with v0.5 (whenever this version is released).
