### ISSUE TITLE
After 13.0 patch not working anymore

### ISSUE THREAD

**Issue by lilosenpai** [Rerago/LoLWideScreenFix#8]
Before, after every patch i had to generate again the file, but after the 13.0 patch, it doesnt generate the wad file anymore

**Comment by Rerago** [comment]
Duplicate to #7

Sorry for the inconvenience. I will go into more detail in the other issue (#7).

**Comment by lilosenpai** [comment]
please dont apologise, your work here i fucking awesome, i was so glad that this existe i that i can play full screen on 32:9, i will await and be thankfull that you are already working on it, u rock
